### Main Page
GET http://localhost:3000/

### Products
GET http://localhost:3000/products

### Product by ID
GET http://localhost:3000/products/6ab2ae362fc1f67f0dcac519

### Update Product
PUT http://localhost:3000/products/6ab2ae362fc1f67f0dcac519
Content-Type: application/json

{
  "name": "Max Potion",
  "category": "Medicine",
  "price": 2500,
  "stock": 5,
  "description": "A spray-type medicine for treating wounds. Fully restores the max HP of a single Pokémon.",
  "inStock": true
}

### Delete Product
DELETE http://localhost:3000/products/6ab2ae362fc1f67f0dcac519


### Render Main
GET https://project1-pcur.onrender.com/

### Render products
GET https://project1-pcur.onrender.com/products

### Render Product by ID
GET https://project1-pcur.onrender.com/products/6ab2ae362fc1f67f0dcac519

